### ISSUE TITLE
headerの描画がうまくいかない。

### ISSUE THREAD

**Issue by naoto-43** [naoto-43/emouta#24]
- 質問内容・実現したいこと
headerがmainと被らないようにしたい。
また、画面上部に固定したい。
最悪cssで画面サイズごとにheaderの高さ分ずらせばできそうかと思いますが、stickyでできない理由がわかりません。
開発環境は以下です。
ruby 3.2.2 ,Rails 7.1.3,node.js v21.6.1,yarn 1.22.19
js : importmap
css : cssbuilding-rails,Tailwind,Daisyui,Flowbite
- 現状発生している問題・エラーメッセージ
flowbiteのコンポーネントでheaderを表示しています。
headerのpositionをstickyにすると被らないけど、上部に固定できない。
fixedにすると固定はできるが、mainと被ってしまう。
- 該当のソースコード
```
<header>
    <nav class="bg-white dark:bg-gray-900 sticky w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
〜
    </nav>
</header>
```
- エラーから考えられる原因
stiskyが機能しないのは親要素がbodyなのが原因？こちらで明示していないがoverflow: hidden;になっている？
- 試したこと
stickyの場合：
親要素（body）にはoverflow: hidden;は指定していません。
```
<!DOCTYPE html>
<html>
  <head>
    <title>Emouta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <% if user_signed_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

```
fixedの場合：
jsでheaderの高さを取得し、その分ずらしてmainを表示しようとしたが、fixedを使うと要素の高さは0になるようなのでダメでした。

**Comment by Tsuchiya2** [comment]
どういった画面になっているのかスクリーンショットを掲載いただくか、デプロイしているURLを共有、加えて見て分かるように説明をいただけると助かります。

状況が分からないため的確ではないことをご了承ください。以下のようにして、<header>要素に固定の高さ(height)を設定して、<div class='contents'>要素では先程設定した分だけ、ページの上部からmarginしたらどうでしょうか？

```
<body>
    <% if user_signed_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <div class='contents'>
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>

**Comment by naoto-43** [comment]
失礼しました。
tailwindインストール後デプロイうまくいっていないためスクリーンショット添付します。
[fixed](https://i.gyazo.com/bcafc147d44ffbb3866faf61b2b108d7.png)
ご提案いただいた方法だと、やはりデバイスサイズごとに明示して調整する形になるでしょうか。
以下のコードでは期待通りに機能するのは確認できました。
```
document.addEventListener("turbo:load", function() {
  function adjustLayout() {
      const mainContent = document.getElementById('main-content');
      if (window.innerWidth < 768) { // 例: スマートフォン
          mainContent.style.paddingTop = '50px'; // ヘッダーの高さに合わせて調整
      } else if (window.innerWidth >= 768 && window.innerWidth < 1024) { // 例: タブレット
          mainContent.style.paddingTop = '70px'; // ヘッダーの高さに合わせて調整
      } else { // 例: デスクトップ
          mainContent.style.paddingTop = '90px'; // ヘッダーの高さに合わせて調整
      }
  }

  // ウィンドウサイズが変更された時にも調整を適用
  window.addEventListener('resize', adjustLayout);

  // 初回読み込み時にレイアウト調整を実行
  adjustLayout();
});

```
ただ現状すでにレスポンシブになっているので、できればjsで動的にheader高さ取得してmarginするか、stickyで上部に固定する方法で実装できないかなと考えていたのですがこれは無駄なこだわりでしょうか。

**Comment by Tsuchiya2** [comment]
スクリーンショットは共有した内容を反映したものなのか、一番最初の状態を反映しているものなのかが記載されていないため評価ができませんが。。

もし期待通りになっているのであれば、クリア状態になっているもので進めてしまったほうが良いかと思います。sticky如何に関わらず、まずは期待している状態にして、他のものが大方片付いた後にstickyでソレを実現する方法を模索するのが良いかと思います。

**Comment by naoto-43** [comment]
失礼しました。
スクリーンショットはfixedでheaderが重なっている状態です。
添付したコードでは解消されています。

おっしゃる通りですね。ひとまず進めることを優先します。
ありがとうございました。
