### ISSUE TITLE
デプロイ先でのTypeError: map.get is not a function

### ISSUE THREAD

**Issue by naoto-43** [naoto-43/emouta#25]
- 質問内容・実現したいこと
デプロイ先でのみTypeError: map.get is not a functionがログインや楽曲紹介のすべてのフォームに対して発生してしまい、何もできない。
- 現状発生している問題・エラーメッセージ
TypeError: map.get is not a function
- どの処理までうまく動いているのか
投稿一覧や楽曲紹介、ログインへの単純なリンクによる画面遷移はできる。
フォームのリクエストが失敗する。
- 該当のソースコード
app/javascript/controllers/form_controller.js
~
    function fetch(map, key) {
        console.log(map);
        console.log(key);
        let values = map.get(key);
        if (!values) {
            values = new Set();
            map.set(key, values);
        }
        return values;
    }
~
- エラーから考えられる原因
デプロイ環境でのみ発生することから、ビルドプロセスになんらかの問題があるのではないかと思います。
また、デプロイをやり直す前にも同様のエラーが出たことがありましたが、その時はnode_modules/@hotwired/stimulus/dist/stimulus.umd.jsの他にnode_modules/@hotwired/stimulus/dist/stimulus.jsのようなファイルが存在し、それを削除することでログインや投稿など正常にできていました。
今回はnode_modules/@hotwired/stimulus/dist/stimulus.umd.jsしか存在しないためどこに問題があるのかわかりません。
- 試したこと
Gemfile.lock,package-lock.jsonを削除し、bundle install,npm install,rails assets:precompileを実行後、再度pushしたがダメでした。

アプリリンク:https://emouta-42c549b6e6eb.herokuapp.com/

**Comment by Tsuchiya2** [comment]
まずコードを共有する際はコードブロックを使用して共有いただきたいです。

以下のファイルが本番環境で正しく読み込まれているかは確認されていますか。
また、以下のコードはいつ読み込まれるのか、いつ実行されるのかなどを確認して、現状どうなっているのか、RailsにおけるJavaScriptの取り扱い方なども調べてみましょう。

```javascript
# app/javascript/controllers/form_controller.js

function fetch(map, key) {
console.log(map);
console.log(key);
let values = map.get(key);
if (!values) {
values = new Set();
map.set(key, values);
}
return values;
}
```

別件になりますがこちらの方法は本当に適切なやり方なのか調べたり考えたりしてみましょう。

> node_modules/@hotwired/stimulus/dist/stimulus.umd.jsの他にnode_modules/@hotwired/stimulus/dist/stimulus.jsのようなファイルが存在し、それを削除することでログインや投稿など正常にできていました。

**Comment by naoto-43** [comment]
失礼しました。以後そのようにします！

https://emouta-42c549b6e6eb.herokuapp.com/assets/application-774e6021e16d78324eac4a272b91635be15479ddb11f1786a4e116eced96ab52.js
このファイルがbuildされたjsファイルで、ここに含まれているということは読み込まれているということではないのでしょうか。

最初の質問でファイル名間違えておりました。
正しくは以下です。
```
node_modules/@hotwired/stimulus/dist/stimulus.umd.js
function fetch(map, key) {
console.log(map);
console.log(key);
let values = map.get(key);
if (!values) {
values = new Set();
map.set(key, values);
}
return values;
}
```
これはstimulusのfetchリクエストが発生した時に実行されるものと考えています。
map.get is not a functionとなっているのでmapではないものを引数として渡そうとしているということだと思うのですが、ログインや楽曲紹介などすべての箇所で、かつデプロイ環境のみで発生するエラーなので根本的な原因はここではなく、ビルドプロセスになんらかの矛盾があるのではと考えました。

別件の方は以前はそれでうまくいったので参考までに書きました。今回は関係ないと思います。

**Comment by Tsuchiya2** [comment]
> node_modules/@hotwired/stimulus/dist/stimulus.umd.jsの他にnode_modules/@hotwired/stimulus/dist/stimulus.jsのようなファイルが存在し、それを削除することでログインや投稿など正常にできていました。

↑の操作が遠因として影響している可能性はいかがでしょうか。本当に影響がないか可能性を潰すように確認をしておきましょう。確固たる確認ができれば、そちらは以後考えなくて良くなるかと思います。一度検証用のアプリケーションを用意するなどして確認してみたり、"仮説・検証・実行"のサイクルを回してみていただけますか。

**Comment by naoto-43** [comment]
ご指摘いただいた部分で検証用アプリを作り、"仮説・検証・実行"で試行錯誤した結果、esbuildで--format=esmを指定しており、node_modules/@hotwired/stimulus/dist/stimulus.jsがバンドルされていることが原因と判明しました。
質問時に勘違いしていたのですがエラー箇所はnode_modules/@hotwired/stimulus/dist/stimulus.umd.jsではなくnode_modules/@hotwired/stimulus/dist/stimulus.jsにありました。
stimulus.jsは削除していたので、ローカルではエラーは出ずエラー箇所も残していてstimulus.umd.jsのファイルのものだと勘違いしてしまいました。
--format=esmオプションによってstimulus.jsとしてビルドされていたのでファイル形式の違いによりデプロイ先ではエラーが発生していたようです。
ご助言ありがとうございました。
