### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [naoto-43/emouta#26]
@naoto-43 
MVPリリースお疲れ様でした。
下記にフィードバックをあげたのでご確認ください。

## フィードバック
- ページネーションにデザインを当てこんておきましょう
- ユーザー登録画面にデザインを当てこんでおきましょう
- ヘッダーメニューの文字が光りすぎて見にくいので、少し色合いを抑えましょう
- フォーム入力部分の文字が薄く見にくいので、文字色を濃いめにする
- spotifyの非同期検索の候補表示部分のUIを修正する（デザインが崩れる&候補の区切りがわかりづらいため）
- 他ユーザーの投稿の編集、削除ボタンが残っているので削除する
- 余計なファイルを消しておく（node_modulesなど）

上記内容をタスクに落とし込んで、issue化できたら再度本リリースまでのスケジュールをこちらのスレッドに共有いただければでございます。
以上よろしくお願いいたします。

**Comment by naoto-43** [comment]
以下本リリースまでのissueです。
ご確認よろしくお願いします。
[](https://github.com/users/naoto-43/projects/3/views/1?filterQuery=-status%3ATodo)
